[phases.setup]
aptPkgs = [
    "libcairo2-dev",
    "pkg-config",
    "python3-dev",
    "libgirepository1.0-dev",
    "build-essential",
    "default-libmysqlclient-dev"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "python -m pip install -r requirements.txt"
]
